### ISSUE TITLE
Reporting possible false positive

### ISSUE THREAD

**Issue by djui** [FiloSottile/vendorcheck#1]
Either the tool actually found a problem with one of my projects or it's a false positive:

I run

```
$ vendorcheck ./...
[!] dependency not vendored: golang.org/x/text/transform
[!] dependency not vendored: golang.org/x/text/encoding/charmap
[!] dependency not vendored: golang.org/x/text/language
[!] dependency not vendored: golang.org/x/text/encoding/internal/identifier
[!] dependency not vendored: golang.org/x/text/encoding
[!] dependency not vendored: golang.org/x/text/encoding/simplifiedchinese
[!] dependency not vendored: golang.org/x/text/internal/utf8internal
[!] dependency not vendored: golang.org/x/text/encoding/korean
[!] dependency not vendored: golang.org/x/text/encoding/unicode
[!] dependency not vendored: golang.org/x/text/encoding/japanese
[!] dependency not vendored: golang.org/x/text/encoding/traditionalchinese
[!] dependency not vendored: golang.org/x/text/runes
[!] dependency not vendored: golang.org/x/text/encoding/htmlindex
[!] dependency not vendored: golang.org/x/text/encoding/internal
[!] dependency not vendored: golang.org/x/text/internal/tag
```

However, I don't use these packages. They are referenced from `vendor/golang.org/x/net/html/charset` of which I vendor `vendor/golang.org/x/net` (but only need `vendor/golang.org/x/net/context` there), which I can't vendor more fine-grained as I use git submodules and I assume Go compiler would complain as well):

```
vendor/golang.org/x/net
|- vendor/golang.org/x/net/context
+- vendor/golang.org/x/net/html/charset
    +- vendor/golang.org/x/text
```

Also, could you change the log output from `[!]` to `Error:` or `Warn:`? Then I think it's easier to integrate the tool into [go-metalinter](https://github.com/alecthomas/gometalinter).

**Comment by FiloSottile** [comment]
It's technically not a false positive, but definitely a bad UX: `./...` matches also everything in `./vendor/...`, so the vendored packages will be scanned for missing dependencies, too.

I'll change this so that `./...` does not match `*/vendor/*`. Thanks for the report.

**Comment by djui** [comment]
Good idea, thanks!
