### ISSUE TITLE
Reports internal package as dependency to vendor

### ISSUE THREAD

**Issue by mvdan** [FiloSottile/vendorcheck#2]
```
 $ go list ./...
github.com/mvdan/interfacer
github.com/mvdan/interfacer/cmd/interfacer
github.com/mvdan/interfacer/generate/std
github.com/mvdan/interfacer/internal/util
github.com/mvdan/interfacer/vendor/github.com/kisielk/gotool
github.com/mvdan/interfacer/vendor/golang.org/x/tools/go/ast/astutil
github.com/mvdan/interfacer/vendor/golang.org/x/tools/go/buildutil
github.com/mvdan/interfacer/vendor/golang.org/x/tools/go/loader
 $ vendorcheck
[!] dependency not vendored: github.com/mvdan/interfacer/internal/util
```

Unless there is something obvious I'm missing here, this sounds like a false positive.

If you have trouble reproducing this, let me know :)

**Comment by mvdan** [comment]
Actually, this got solved by using `vendorcheck ./...` instead. Is this expected?

**Comment by iambrosie** [comment]
I'm not affiliated with the project, but according to the [README.md](https://github.com/FiloSottile/vendorcheck/blob/master/README.md), this is indeed what you should be using.

Regards.

**Comment by FiloSottile** [comment]
Ah, we should ignore subpackages of initial packages, yes.
